// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var topNodeOptions = []prompt.Suggest{
	{Text: "--no-headers", Description: "If present, print output without headers"},
	{Text: "-l", Description: "Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)"},
	{Text: "--selector", Description: "Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)"},
	{Text: "--show-capacity", Description: "Print node resources based on Capacity instead of Allocatable(default) of the nodes."},
	{Text: "--sort-by", Description: "If non-empty, sort nodes list using specified field. The field can be either 'cpu' or 'memory'."},
	{Text: "--use-protocol-buffers", Description: "Enables using protocol-buffers to access Metrics API."},
}
